services:
  transcoding-server:
    image: alfg/nginx-rtmp
    container_name: transcoding-server
    ports:
      - "1935:1935"
      - "8081:80"
    environment:
      HTTP_PORT: 80
      RTMP_PORT: 1935
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ../data:/opt/data
