services:
  transcoding-server:
    image: transcoding-server
    container_name: transcoding-server
    ports:
      - "1935:1935"
      - "8081:80"
    environment:
      HTTP_PORT: 80
      RTMP_PORT: 1935
    volumes:
      - ./nginx-cuda.conf:/etc/nginx/nginx.conf.template
      - ../data:/opt/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]
